server:
  port: 8081
spring:
#Database / Hibernate / JPA
  datasource:
    url: jdbc:mysql://localhost:3306/nfjuara?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    driver: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    
  flyway:
    location: C:\\Users\\Fahd\\Documents\\Project\\baru\\NFJuara2\\src\\main\\resources\\db\\migration
#spring.flyway.locations=C:\\Users\\Fahd\\Documents\\Project\\baru\\NFJuara2\\src\\main\\resources\\db\\migration